name: Build Custom Telegram

on:
  push:
    branches: [ master, main ]
  workflow_dispatch: # Emon ekta button add korbe jeta diye manually build start kora jay

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive # Telegram er onnek submodule ache, gulo pull kora joruri

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' # Telegram Android 17 e kaj kore

      - name: Inject API ID and HASH
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
        run: |
          # BuildVars.java file e dummy API key change kore tomar secret key bosano hocche
          FILE="TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java"
          if [ -f "$FILE" ]; then
            sed -i "s/APP_ID = .*/APP_ID = $TG_API_ID;/g" $FILE
            sed -i "s/APP_HASH = .*/APP_HASH = \"$TG_API_HASH\";/g" $FILE
          fi

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build APK (Standalone Debug)
        run: bash ./gradlew assembleStandaloneDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ZdCustomGram-APK
          path: TMessagesProj/build/outputs/apk/*/debug/*.apk
